#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, '..');

const parts = [
  'src/state.js',
  'src/manual-tools.js',
  'src/auto-detection.js',
  'src/auto-drafts.js',
  'src/rendering.js',
];

const generatedHeader = `// Generated by scripts/build-app.mjs. Edit src/*.js instead.\n(() => {\n  'use strict';\n\n`;
const generatedFooter = `\n\n  init();\n})();\n`;

const body = parts.map((part) => {
  const source = readFileSync(path.join(appDir, part), 'utf8').trimEnd();
  return `  // ---- ${part} ----\n${source}\n`;
}).join('\n');

const bundle = generatedHeader + body + generatedFooter;

// Parse-only validation. This does not execute browser code.
try {
  // eslint-disable-next-line no-new-func
  new Function(bundle);
} catch (error) {
  console.error('Generated app.js failed parse validation.');
  console.error(error && error.stack ? error.stack : String(error));
  process.exit(1);
}

writeFileSync(path.join(appDir, 'app.js'), bundle);
console.log(`built app.js from ${parts.length} source parts`);
