#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SOURCE_PARTS, AUTO_SEAM_WORKER_PARTS, DXF_WORKER_PARTS } from './source-parts.mjs';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, '..');

// --verify: assemble both bundles in memory and compare them byte-for-byte to
// the committed app.js / auto-seam-worker.js WITHOUT writing. Exits non-zero
// if they differ so callers (npm run check) can catch a src/* edit that was
// never rebuilt. We compare bytes, not mtimes, because this repo lives on a
// Google Drive mount that rewrites mtimes on sync — mtime freshness checks are
// unreliable here.
const verifyOnly = process.argv.slice(2).includes('--verify');

const builtInRuleJson = {
  version: readJson('auto_mode_rules/version.json'),
  pomTemplate: readJson('auto_mode_rules/pom-template.json'),
  anchorSchema: readJson('auto_mode_rules/anchor-schema.json'),
  sizeLSuggestions: readJson('auto_mode_rules/sizeL-suggestions.json'),
};

// ---------------------------------------------------------------------------
// Bundle 1 of 2 — auto-seam-worker.js (US-120). Built FIRST because app.js
// embeds this bundle's content hash as the worker URL, so the app hash (and
// its index.html cache-buster) changes whenever the worker changes.
const workerHeader = '// Generated by scripts/build-app.mjs from AUTO_SEAM_WORKER_PARTS (scripts/source-parts.mjs). Edit src/*.js instead.\n'
  + '// US-120 Auto Seam Worker: the pure src/auto/seam/* parts app.js also ships, plus worker-entry.js.\n'
  + "(() => {\n  'use strict';\n\n";
const workerFooter = '\n})();\n';
const workerBundle = workerHeader + concatParts(AUTO_SEAM_WORKER_PARTS) + workerFooter;
parseOrExit(workerBundle, 'auto-seam-worker.js');
const WORKER_CACHE_BUSTER = shortHash(workerBundle);
const WORKER_URL = `auto-seam-worker.js?v=${WORKER_CACHE_BUSTER}`;

// ---------------------------------------------------------------------------
// Bundle 2 of 3 — dxf-worker.js (US-124 Phase 5, ADR 0091). Same rule as the
// seam worker: built before app.js because app.js embeds its content hash.
const dxfWorkerHeader = '// Generated by scripts/build-app.mjs from DXF_WORKER_PARTS (scripts/source-parts.mjs). Edit src/*.js instead.\n'
  + '// US-124 DXF Worker: the pure DXF parse layer app.js also ships (math, pattern classifier, dxf-parse, native parser), plus dxf-worker-entry.js.\n'
  + "(() => {\n  'use strict';\n\n";
const dxfWorkerBundle = dxfWorkerHeader + concatParts(DXF_WORKER_PARTS) + workerFooter;
parseOrExit(dxfWorkerBundle, 'dxf-worker.js');
const DXF_WORKER_CACHE_BUSTER = shortHash(dxfWorkerBundle);
const DXF_WORKER_URL_VALUE = `dxf-worker.js?v=${DXF_WORKER_CACHE_BUSTER}`;

// ---------------------------------------------------------------------------
// Bundle 3 of 3 — app.js.
const generatedHeader = `// Generated by scripts/build-app.mjs. Edit src/*.js instead.\n(() => {\n  'use strict';\n\n  const BUILTIN_AUTO_MODE_RULE_JSON = ${JSON.stringify(builtInRuleJson)};\n\n`
  + `  // US-120: URL of the Auto Seam Worker bundle, content-hashed like app.js?v=.\n  const AUTO_SEAM_WORKER_URL = ${JSON.stringify(WORKER_URL)};\n\n`
  + `  // US-124: URL of the DXF Worker bundle, content-hashed like app.js?v=.\n  const DXF_WORKER_URL = ${JSON.stringify(DXF_WORKER_URL_VALUE)};\n\n`;
const generatedFooter = `\n\n  init();\n})();\n`;
const bundle = generatedHeader + concatParts(SOURCE_PARTS) + generatedFooter;
parseOrExit(bundle, 'app.js');

const appPath = path.join(appDir, 'app.js');
const workerPath = path.join(appDir, 'auto-seam-worker.js');
const dxfWorkerPath = path.join(appDir, 'dxf-worker.js');

// Cache-buster for the <script src="app.js?v=..."> tag in index.html. It is a
// content hash of the bundle, so it changes whenever app.js changes and stays
// stable when it doesn't. A STATIC ?v= (the old hard-coded string) meant every
// rebuild shipped a fresh app.js under the same URL, so browsers and the GitHub
// Pages CDN kept serving the previously cached (stale) app.js indefinitely —
// users saw pre-fix behavior long after a fix landed. Hashing the query fixes
// that: a changed bundle => a new URL => clients fetch it. index.html is not
// part of the bundle, so rewriting its tag cannot feed back into the hash.
const APP_CACHE_BUSTER = shortHash(bundle);
const indexPath = path.join(appDir, 'index.html');
const APP_TAG_RE = /(<script src="app\.js\?v=)[^"]*(">)/;

function readIndexHtml() {
  return existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : null;
}

function currentIndexCacheBuster(html) {
  if (html == null) return null;
  const m = html.match(/<script src="app\.js\?v=([^"]*)">/);
  return m ? m[1] : null;
}

if (verifyOnly) {
  const currentWorker = existsSync(workerPath) ? readFileSync(workerPath, 'utf8') : null;
  if (currentWorker !== workerBundle) {
    console.error('auto-seam-worker.js is stale — it does not match src/auto/seam/*. Run `npm run build`.');
    process.exit(1);
  }
  const currentDxfWorker = existsSync(dxfWorkerPath) ? readFileSync(dxfWorkerPath, 'utf8') : null;
  if (currentDxfWorker !== dxfWorkerBundle) {
    console.error('dxf-worker.js is stale — it does not match DXF_WORKER_PARTS. Run `npm run build`.');
    process.exit(1);
  }
  const current = existsSync(appPath) ? readFileSync(appPath, 'utf8') : null;
  if (current !== bundle) {
    console.error('app.js is stale — it does not match src/*. Run `npm run build`.');
    process.exit(1);
  }
  const html = readIndexHtml();
  const buster = currentIndexCacheBuster(html);
  if (buster !== APP_CACHE_BUSTER) {
    console.error(
      `index.html app.js cache-buster is stale (found "${buster}", expected "${APP_CACHE_BUSTER}"). Run \`npm run build\`.`
    );
    process.exit(1);
  }
  console.log('app.js is up to date with src/* (cache-buster ' + APP_CACHE_BUSTER + ', seam worker ' + WORKER_CACHE_BUSTER + ', dxf worker ' + DXF_WORKER_CACHE_BUSTER + ')');
  process.exit(0);
}

writeFileSync(workerPath, workerBundle);
console.log(`built auto-seam-worker.js from ${AUTO_SEAM_WORKER_PARTS.length} source parts (cache-buster ${WORKER_CACHE_BUSTER})`);
writeFileSync(dxfWorkerPath, dxfWorkerBundle);
console.log(`built dxf-worker.js from ${DXF_WORKER_PARTS.length} source parts (cache-buster ${DXF_WORKER_CACHE_BUSTER})`);
writeFileSync(appPath, bundle);
console.log(`built app.js from ${SOURCE_PARTS.length} source parts`);

// Sync index.html's app.js cache-buster to the new bundle hash.
const html = readIndexHtml();
if (html != null) {
  if (!APP_TAG_RE.test(html)) {
    console.error('index.html has no <script src="app.js?v=..."> tag to update.');
    process.exit(1);
  }
  const nextHtml = html.replace(APP_TAG_RE, `$1${APP_CACHE_BUSTER}$2`);
  if (nextHtml !== html) {
    writeFileSync(indexPath, nextHtml);
    console.log(`updated index.html app.js cache-buster -> ${APP_CACHE_BUSTER}`);
  } else {
    console.log(`index.html app.js cache-buster already current (${APP_CACHE_BUSTER})`);
  }
}

function concatParts(parts) {
  return parts.map((part) => {
    const source = readFileSync(path.join(appDir, part), 'utf8').trimEnd();
    return `  // ---- ${part} ----\n${source}\n`;
  }).join('\n');
}

// Parse-only validation. This does not execute browser code.
function parseOrExit(source, name) {
  try {
    // eslint-disable-next-line no-new-func
    new Function(source);
  } catch (error) {
    console.error(`Generated ${name} failed parse validation.`);
    console.error(error && error.stack ? error.stack : String(error));
    process.exit(1);
  }
}

function shortHash(text) {
  return createHash('sha256').update(text).digest('hex').slice(0, 12);
}

function readJson(relativePath) {
  return JSON.parse(readFileSync(path.join(appDir, relativePath), 'utf8'));
}
