// Shared manifest of source parts that scripts/build-app.mjs concatenates
// into app.js. scripts/check.mjs parses the same list to verify each part is
// syntactically valid in isolation. Keep this file as the only place the
// ordering and membership of the bundle is declared.
//
// Order matters: the parts are concatenated into a single IIFE and share
// scope, so a part that uses a name defined elsewhere must appear after the
// part that defines it. See README.md "Code layout" for the high-level map.

export const SOURCE_PARTS = [
  'src/auto/rules/load-rules.js',
  'src/state.js',
  'src/dom-refs.js',
  'src/project/grade-rules.js',
  'src/auto/telemetry/session-stats.js',
  'src/auto/telemetry/session-timer.js',
  'src/curves.js',
  'src/geometry/math.js',
  'src/geometry/dxf-path-kernel.js',
  'src/manual/board-graphics.js',
  'src/ui/toast.js',
  'src/ui/dialogs/core.js',
  'src/ui/dialogs/command-palette-dialog.js',
  'src/ui/dialogs/help-dialog.js',
  'src/ui/dialogs/scale-dialog.js',
  'src/ui/dialogs/auto-exit-dialog.js',
  'src/ui/dialogs/save-evidence-dialog.js',
  'src/ui/dialogs/learning-data-shared.js',
  'src/ui/dialogs/learning-data-tabs.js',
  'src/ui/dialogs/learning-data-telemetry.js',
  'src/ui/dialogs/learning-data-summary.js',
  'src/ui/dialogs/learning-data-corrections.js',
  'src/ui/dialogs/learning-data-meanings.js',
  'src/ui/dialogs/learning-data-evidence.js',
  'src/ui/dialogs/learning-data-dialog.js',
  'src/ui/dialogs/library-shared.js',
  'src/ui/dialogs/library-list-view.js',
  'src/ui/dialogs/library-grid-view.js',
  'src/ui/dialogs/library-dialog.js',
  'src/ui/dialogs/library-manager-dialog.js',
  'src/ui/dialogs/grading-rules-model.js',
  'src/ui/dialogs/size-run-dialog.js',
  'src/ui/dialogs/export-size-dialog.js',
  'src/ui/dialogs/grading-dialog.js',
  'src/ui/dialogs/view-roles-dialog.js',
  'src/auto/measure/fusion.js',
  'src/ui/spec-visibility.js',
  'src/ui/spec-values.js',
  'src/ui/spec-row-builders.js',
  'src/ui/spec-panel.js',
  'src/ui/draggable-panel.js',
  'src/ui/anchor-manager-panel.js',
  'src/ui/main-page-data.js',
  'src/ui/main-page-sketches.js',
  'src/ui/main-page-fields.js',
  'src/ui/main-page-colorways.js',
  'src/ui/main-page.js',
  'src/ui/construction-phrase-data.js',
  'src/ui/construction-state.js',
  'src/ui/construction-images.js',
  'src/ui/construction-canvas.js',
  'src/ui/construction-rows.js',
  'src/ui/construction.js',
  'src/ui/bom-material-data.js',
  'src/ui/bom-state.js',
  'src/ui/bom-images.js',
  'src/ui/bom-materials.js',
  'src/ui/bom-canvas.js',
  'src/ui/bom-table.js',
  'src/ui/bom.js',
  'src/ui/preview-page.js',
  'src/ui/page-nav.js',
  'src/ui/command-registry.js',
  'src/ui/board-toolbar.js',
  'src/ui/label-editor.js',
  'src/ui/note-editor.js',
  'src/ui/line-preset-panel.js',
  'src/ui/shape-stamp-panel.js',
  'src/ui/dxf-measure-panel.js',
  'src/manual/simplify-piece.js',
  'src/ui/pattern-pieces-panel.js',
  'src/ui/dxf-measurements-panel.js',
  'src/ui/bindings.js',
  'src/project/dxf-pattern-source.js',
  'src/project/history.js',
  'src/project/project-save.js',
  'src/project/project-load.js',
  'src/project/autosave.js',
  'src/ui/dialogs/autosave-restore-banner.js',
  'src/project/project-library.js',
  'src/import/zip-reader.js',
  'src/import/pptx-xml.js',
  'src/ui/dialogs/pptx-picker-dialog.js',
  'src/import/pptx.js',
  'src/manual/annotation-factory.js',
  'src/manual/label-layout.js',
  'src/manual/annotation-lifecycle.js',
  'src/manual/annotation-clipboard.js',
  'src/manual/selection.js',
  'src/manual/smart-align.js',
  'src/manual/pointer-events.js',
  'src/manual/touch-input.js',
  'src/manual/canvas-tools.js',
  'src/manual/line-nudge.js',
  'src/manual/keyboard-shortcuts.js',
  'src/manual/format.js',
  'src/manual/style.js',
  'src/manual/sketch-mode.js',
  'src/manual/mindmap-mode.js',
  'src/manual/library-store.js',
  'src/manual/line-presets.js',
  'src/manual/shape-stamps.js',
  'src/manual/dxf-import.js',
  'src/manual/dxf-native-parser.js',
  'src/manual/dxf-measure-session.js',
  'src/manual/dxf-measure-snap.js',
  'src/manual/dxf-measure-interaction.js',
  'src/manual/viewport.js',
  'src/manual/image-records.js',
  'src/manual/ui-status.js',
  'src/manual/image-import.js',
  'src/manual/annotation-lookup.js',
  'src/manual/note-model.js',
  'src/manual/notches.js',
  'src/auto/mode.js',
  'src/auto/detect/junctions.js',
  'src/auto/detect/landmark-qa.js',
  'src/auto/detect/math-utils.js',
  'src/auto/detect/ink-mask.js',
  'src/auto/detect/view-boxes.js',
  'src/auto/detect/segmentation.js',
  'src/auto/detect/potrace-trace.js',
  'src/auto/detect/geometry-stage.js',
  'src/auto/detect/front-landmarks.js',
  'src/auto/detect/cup-model.js',
  'src/auto/detect/back-landmarks.js',
  'src/auto/detect/pom6-cradle-cf.js',
  'src/auto/detect/pom7-cradle-cup.js',
  'src/auto/detect/cv-debug-payload.js',
  'src/auto/detect/landmark-stage.js',
  'src/auto-detection.js',
  'src/auto/anchors/seed-view-resolution.js',
  'src/auto/anchors/seed-cradle-cf.js',
  'src/auto/anchors/seed-cup-width.js',
  'src/auto/anchors/seed-front-view.js',
  'src/auto/anchors/seed-back-view.js',
  'src/auto/anchors/seed-anchors.js',
  'src/auto/mode/offline-detection-run.js',
  'src/auto/anchors/derive-anchors.js',
  'src/auto/anchors/anchor-visibility.js',
  'src/auto/anchors/anchor-interaction.js',
  'src/auto/drafts/view-role-helpers.js',
  'src/auto/drafts/pom-fixture-builder.js',
  'src/auto/drafts/anchor-drag-sync.js',
  'src/auto/drafts/build-draft-annotation.js',
  'src/auto/drafts/validate-fixture.js',
  'src/auto/drafts/draft-actions.js',
  'src/auto/drafts/apply-drafts.js',
  // Auto Seam (US-109): listed in dependency order — contract/pixel model,
  // classifier, shared corridor + result records, the lanes, the router, then
  // the one part that touches Board state. Order is documentation here (every
  // symbol is a hoisted function); see docs/stories/epics/E07-measurement-detection/
  // US-109-photo-zigzag-detection/CODE_STRUCTURE.md.
  'src/auto/seam/contract.js',
  'src/auto/seam/thresholds.js',
  'src/auto/seam/pixel-model.js',
  'src/auto/seam/input-classifier.js',
  'src/auto/seam/corridor.js',
  'src/auto/seam/pattern-evidence.js',
  'src/auto/seam/edge-band.js',
  'src/auto/seam/geometry.js',
  'src/auto/seam/result.js',
  'src/auto/seam/lanes/product-photo.js',
  'src/auto/seam/lanes/technical-flat.js',
  'src/auto/seam/router.js',
  // US-120: main-thread client that runs the router above inside the Auto Seam
  // Worker (auto-seam-worker.js) and falls back to the same code in-thread.
  'src/manual/auto-seam-worker-client.js',
  'src/manual/auto-seam.js',
  // US-121: TD Review loop (Phase C first slice) — Board-touching, app.js
  // only (never the worker bundle). Needs makeDraggablePanel (ui/draggable-
  // panel.js, loaded earlier) and autoSeamSourceSha256 (auto-seam.js, just
  // above); read by src/render/auto-seam-review-overlay.js below.
  'src/manual/auto-seam-review.js',
  'src/auto/drafts/board-reset.js',
  'src/auto/drafts/generate-drafts-action.js',
  'src/auto/learning/acceptance-stats.js',
  'src/auto/learning/calibration-store.js',
  'src/auto/learning/shadow-detection.js',
  'src/auto/learning/meaning-store.js',
  'src/auto/learning/meaning-commit.js',
  'src/auto/learning/style-evidence-record.js',
  'src/auto/learning/style-evidence-capture.js',
  'src/auto/learning/style-evidence-reuse.js',
  'src/auto/debug-export.js',
  'src/auto/debug-api.js',
  'src/render/export-pdf.js',
  'src/render/copy-image.js',
  'src/render/export-xlsx-grading.js',
  'src/render/xlsx-writer.js',
  'src/render/export-spec-xlsx.js',
  'src/render/export-techpack-xlsx.js',
  'src/render/hit-testing.js',
  'src/render/render-stitches.js',
  'src/render/render-annotations.js',
  'src/render/render-notes.js',
  'src/render/render-dxf-measurements.js',
  'src/render/detection-overlay.js',
  'src/render/auto-seam-review-overlay.js',
  'src/render/anchor-pins.js',
  'src/render/render-images.js',
  'src/render/viewport.js',
  'src/render/render-loop.js',
  'src/bootstrap.js',
  'src/dev/url-bootstrap.js',
];

// US-120: the second bundle. scripts/build-app.mjs concatenates these into
// auto-seam-worker.js, which app.js loads as a Web Worker. It is the pure
// src/auto/seam/* pipeline (every part that app.js also ships — the SAME
// files, so both bundles run identical detection code) plus one worker-only
// entry part that is deliberately NOT in SOURCE_PARTS. The worker bundle has
// its own shared scope, so scripts/check.mjs validates it separately.
export const AUTO_SEAM_WORKER_PARTS = [
  ...SOURCE_PARTS.filter(part => part.startsWith('src/auto/seam/')),
  'src/auto/seam/worker-entry.js',
];
