// Shared manifest of source parts that scripts/build-app.mjs concatenates
// into app.js. scripts/check.mjs parses the same list to verify each part is
// syntactically valid in isolation. Keep this file as the only place the
// ordering and membership of the bundle is declared.
//
// Order matters: the parts are concatenated into a single IIFE and share
// scope, so a part that uses a name defined elsewhere must appear after the
// part that defines it. See README.md "Code layout" for the high-level map.

export const SOURCE_PARTS = [
  'src/auto/rules/load-rules.js',
  'src/state.js',
  'src/auto/telemetry/session-stats.js',
  'src/auto/telemetry/session-timer.js',
  'src/curves.js',
  'src/geometry/math.js',
  'src/ui/toast.js',
  'src/ui/dialogs/core.js',
  'src/ui/dialogs/help-dialog.js',
  'src/ui/dialogs/scale-dialog.js',
  'src/ui/dialogs/auto-exit-dialog.js',
  'src/ui/dialogs/save-evidence-dialog.js',
  'src/ui/dialogs/learning-data-dialog.js',
  'src/ui/dialogs/library-dialog.js',
  'src/ui/dialogs/size-run-dialog.js',
  'src/ui/dialogs/export-size-dialog.js',
  'src/ui/dialogs/grading-dialog.js',
  'src/ui/dialogs/view-roles-dialog.js',
  'src/auto/measure/fusion.js',
  'src/ui/spec-panel.js',
  'src/ui/main-page.js',
  'src/ui/construction-phrase-data.js',
  'src/ui/construction.js',
  'src/ui/bom-material-data.js',
  'src/ui/bom.js',
  'src/ui/preview-page.js',
  'src/ui/page-nav.js',
  'src/ui/board-toolbar.js',
  'src/ui/bindings.js',
  'src/project/history.js',
  'src/project/project-io.js',
  'src/project/autosave.js',
  'src/project/project-library.js',
  'src/import/pptx.js',
  'src/manual/annotations.js',
  'src/manual/interactions.js',
  'src/manual/format.js',
  'src/manual/style.js',
  'src/manual/viewport.js',
  'src/manual/image-records.js',
  'src/manual-tools.js',
  'src/auto/mode.js',
  'src/auto/detect/junctions.js',
  'src/auto/detect/landmark-qa.js',
  'src/auto-detection.js',
  'src/auto/anchors/seed-anchors.js',
  'src/auto/anchors/derive-anchors.js',
  'src/auto/anchors/anchor-interaction.js',
  'src/auto/drafts/generate-pom-fixture.js',
  'src/auto/drafts/build-draft-annotation.js',
  'src/auto/drafts/validate-fixture.js',
  'src/auto/drafts/draft-actions.js',
  'src/auto/learning/acceptance-stats.js',
  'src/auto/learning/calibration-store.js',
  'src/auto/learning/meaning-store.js',
  'src/auto/learning/style-evidence-store.js',
  'src/auto/debug-api.js',
  'src/render/export-pdf.js',
  'src/render/copy-image.js',
  'src/render/export-xlsx.js',
  'src/render/hit-testing.js',
  'src/render/render-stitches.js',
  'src/render/render-annotations.js',
  'src/render/render-auto-overlay.js',
  'src/render/render-images.js',
  'src/render/render-loop.js',
];
