// DOM element handle registry.
// Source part for app.js. Run `npm run build` after editing.

  const el = {
    canvas: document.getElementById('boardCanvas'),
    boardCard: document.getElementById('boardCard'),
    boardEmptyImport: document.getElementById('boardEmptyImport'),
    boardEmptyAdd: document.getElementById('boardEmptyAdd'),
    addImageBtn: document.getElementById('addImageBtn'),
    imageFileInput: document.getElementById('imageFileInput'),
    helpBtn: document.getElementById('helpBtn'),
    toolSelect: document.getElementById('toolSelect'),
    toolStraight: document.getElementById('toolStraight'),
    toolCurved: document.getElementById('toolCurved'),
    toolEraser: document.getElementById('toolEraser'),
    toolText: document.getElementById('toolText'),
    toolRectangle: document.getElementById('toolRectangle'),
    toolCircle: document.getElementById('toolCircle'),
    toolHexagon: document.getElementById('toolHexagon'),
    smartAlignToggleBtn: document.getElementById('smartAlignToggleBtn'),
    // US-093 / ADR 0053: Straight/Curved/Eraser/Text moved into one drop-down
    // to free this slot — see toolsMenuBtn below.
    toolAddPoint: document.getElementById('toolAddPoint'),
    lineStyleControl: document.getElementById('lineStyleControl'),
    stitchesBtn: document.getElementById('stitchesBtn'),
    stitchesBtnLabel: document.getElementById('stitchesBtnLabel'),
    stitchesMenu: document.getElementById('stitchesMenu'),
    styleOptionBtns: Array.from(document.querySelectorAll('.style-option')),
    // US-096 / ADR 0055, US-107: Save as new treatment… and Customize
    // selected… stay in the Stitches menu (board-selection-dependent quick
    // actions) — browsing/picking/managing saved Treatments is the unified
    // Library dialog now (src/ui/dialogs/library-manager-dialog.js), which
    // looks up #linePresetFileInput on demand rather than caching it here.
    linePresetSaveBtn: document.getElementById('linePresetSaveBtn'),
    lineTreatmentCustomizeBtn: document.getElementById('lineTreatmentCustomizeBtn'),
    linePresetFileInput: document.getElementById('linePresetFileInput'),
    // US-097 / ADR 0056, US-107: Save selection as Template… stays in the
    // Tools menu for the same reason. Browsing/picking/managing saved
    // Templates is the unified Library dialog now.
    shapeStampSaveBtn: document.getElementById('shapeStampSaveBtn'),
    shapeStampFileInput: document.getElementById('shapeStampFileInput'),
    // US-104: the "Open DXF file" action, inside the Tools menu.
    dxfImportBtn: document.getElementById('dxfImportBtn'),
    dxfImportFileInput: document.getElementById('dxfImportFileInput'),
    // US-105: the Pattern Measure tool entries, inside the Tools menu.
    dxfMeasureAlongBtn: document.getElementById('dxfMeasureAlongBtn'),
    dxfMeasureOutBtn: document.getElementById('dxfMeasureOutBtn'),
    // US-112: Pattern Measure snap preference toggles, in the same menu.
    dxfMeasureSnapEndpointBtn: document.getElementById('dxfMeasureSnapEndpointBtn'),
    dxfMeasureSnapMidpointBtn: document.getElementById('dxfMeasureSnapMidpointBtn'),
    dxfMeasureSnapIntersectionBtn: document.getElementById('dxfMeasureSnapIntersectionBtn'),
    // US-114: the Pattern-Measure-only active-size filter, same menu.
    dxfMeasureSizeWrap: document.getElementById('dxfMeasureSizeWrap'),
    dxfMeasureSizeSelect: document.getElementById('dxfMeasureSizeSelect'),
    // ADR 0073: the DXF native-unit select + provenance note beside them.
    dxfMeasureUnitSelect: document.getElementById('dxfMeasureUnitSelect'),
    dxfMeasureUnitNote: document.getElementById('dxfMeasureUnitNote'),
    // ADR 0070: the Pattern Pieces panel — Tools menu entry + the floating
    // panel itself, mirroring the anchorManager* refs above.
    patternPiecesBtn: document.getElementById('patternPiecesBtn'),
    patternPiecesPanel: document.getElementById('patternPiecesPanel'),
    patternPiecesHead: document.getElementById('patternPiecesHead'),
    patternPiecesCloseBtn: document.getElementById('patternPiecesCloseBtn'),
    patternPiecesCount: document.getElementById('patternPiecesCount'),
    patternPiecesBody: document.getElementById('patternPiecesBody'),
    patternPiecesApplyBtn: document.getElementById('patternPiecesApplyBtn'),
    // US-113: Pattern Measurements list panel.
    dxfMeasurementsListBtn: document.getElementById('dxfMeasurementsListBtn'),
    dxfMeasurementsPanel: document.getElementById('dxfMeasurementsPanel'),
    dxfMeasurementsHead: document.getElementById('dxfMeasurementsHead'),
    dxfMeasurementsCloseBtn: document.getElementById('dxfMeasurementsCloseBtn'),
    dxfMeasurementsCount: document.getElementById('dxfMeasurementsCount'),
    dxfMeasurementsBody: document.getElementById('dxfMeasurementsBody'),
    dxfMeasurementsClearAllBtn: document.getElementById('dxfMeasurementsClearAllBtn'),
    // ADR 0071: the Notch tool's Tools-menu entry.
    notchToolBtn: document.getElementById('notchToolBtn'),
    lineWidthChip: document.getElementById('lineWidthChip'),
    lineWidthInput: document.getElementById('lineWidthInput'),
    fontSizeChip: document.getElementById('fontSizeChip'),
    fontSizeInput: document.getElementById('fontSizeInput'),
    noteStyleMenuWrap: document.getElementById('noteStyleMenuWrap'),
    noteStyleMenuBtn: document.getElementById('noteStyleMenuBtn'),
    noteStyleMenuList: document.getElementById('noteStyleMenuList'),
    noteAppearanceTextOnlyBtn: document.getElementById('noteAppearanceTextOnlyBtn'),
    noteAppearanceBoxBtn: document.getElementById('noteAppearanceBoxBtn'),
    noteTextColorBtns: Array.from(document.querySelectorAll('.note-text-color-btn')),
    noteLeaderColorBtns: Array.from(document.querySelectorAll('.note-leader-color-btn')),
    brushSizeChip: document.getElementById('brushSizeChip'),
    brushSizeInput: document.getElementById('brushSizeInput'),
    arrowDoubleBtn: document.getElementById('arrowDoubleBtn'),
    arrowSingleBtn: document.getElementById('arrowSingleBtn'),
    arrowNoneBtn: document.getElementById('arrowNoneBtn'),
    colorRedBtn: document.getElementById('colorRedBtn'),
    colorBlueBtn: document.getElementById('colorBlueBtn'),
    colorBlackBtn: document.getElementById('colorBlackBtn'),
    colorWhiteBtn: document.getElementById('colorWhiteBtn'),
    undoBtn: document.getElementById('undoBtn'),
    redoBtn: document.getElementById('redoBtn'),
    copyLineBtn: document.getElementById('copyLineBtn'),
    pasteLineBtn: document.getElementById('pasteLineBtn'),
    reflectLineBtn: document.getElementById('reflectLineBtn'),
    deleteBtn: document.getElementById('deleteBtn'),
    editPathBtn: document.getElementById('editPathBtn'),
    cutPathBtn: document.getElementById('cutPathBtn'),
    segmentStraightBtn: document.getElementById('segmentStraightBtn'),
    segmentCurvedBtn: document.getElementById('segmentCurvedBtn'),
    clearBtn: document.getElementById('clearBtn'),
    lockImageBtn: document.getElementById('lockImageBtn'),
    lockImageLabel: document.getElementById('lockImageLabel'),
    lockImageIco: document.getElementById('lockImageIco'),
    fitBtn: document.getElementById('fitBtn'),
    togglePanelBtn: document.getElementById('togglePanelBtn'),
    toggleLabelsBtn: document.getElementById('toggleLabelsBtn'),
    workspace: document.querySelector('.workspace'),
    setScaleBtn: document.getElementById('setScaleBtn'),
    clearScaleBtn: document.getElementById('clearScaleBtn'),
    // US-104 round 8: same calibration, a second Sketch-Focus-visible
    // entry point (the More menu housing setScaleBtn is Sketch-Focus-hidden).
    sketchSetScaleBtn: document.getElementById('sketchSetScaleBtn'),
    sketchClearScaleBtn: document.getElementById('sketchClearScaleBtn'),
    sizeRunBtn: document.getElementById('sizeRunBtn'),
    gradingBtn: document.getElementById('gradingBtn'),
    exportPdfBtn: document.getElementById('exportPdfBtn'),
    exportExcelBtn: document.getElementById('exportExcelBtn'),
    copyImageBtn: document.getElementById('copyImageBtn'),
    importPptxBtn: document.getElementById('importPptxBtn'),
    pptxFileInput: document.getElementById('pptxFileInput'),
    saveProjectBtn: document.getElementById('saveProjectBtn'),
    openProjectBtn: document.getElementById('openProjectBtn'),
    libraryBtn: document.getElementById('libraryBtn'),
    projectFileInput: document.getElementById('projectFileInput'),
    labelEditor: document.getElementById('labelEditor'),
    // US-092: a TEXTAREA, not an input — a note is multi-line by design, which
    // is the whole reason it cannot reuse #labelEditor.
    noteEditor: document.getElementById('noteEditor'),
    specBody: document.getElementById('specBody'),
    specEmpty: document.getElementById('specEmpty'),
    specCal: document.getElementById('specCal'),
    toolStatus: document.getElementById('toolStatus'),
    imageStatus: document.getElementById('imageStatus'),
    countStatus: document.getElementById('countStatus'),
    toast: document.getElementById('toast'),
    modeManualBtn: document.getElementById('modeManualBtn'),
    modeAutoBtn: document.getElementById('modeAutoBtn'),
    sketchFocusBtn: document.getElementById('sketchFocusBtn'),
    autoModeBar: document.getElementById('autoModeBar'),
    autoDetectBtn: document.getElementById('autoDetectBtn'),
    autoResetAnchorsBtn: document.getElementById('autoResetAnchorsBtn'),
    autoManageAnchorsBtn: document.getElementById('autoManageAnchorsBtn'),
    anchorManagerPanel: document.getElementById('anchorManagerPanel'),
    anchorManagerBody: document.getElementById('anchorManagerBody'),
    anchorManagerCount: document.getElementById('anchorManagerCount'),
    anchorManagerCloseBtn: document.getElementById('anchorManagerCloseBtn'),
    anchorManagerHideAllBtn: document.getElementById('anchorManagerHideAllBtn'),
    anchorManagerShowAllBtn: document.getElementById('anchorManagerShowAllBtn'),
    autoGenerateBtn: document.getElementById('autoGenerateBtn'),
    autoApproveBtn: document.getElementById('autoApproveBtn'),
    autoReviewOnlyBtn: document.getElementById('autoReviewOnlyBtn'),
    autoApplyBtn: document.getElementById('autoApplyBtn'),
    autoDiscardBtn: document.getElementById('autoDiscardBtn'),
    autoResetBoardBtn: document.getElementById('autoResetBoardBtn'),
    autoLearnToggleBtn: document.getElementById('autoLearnToggleBtn'),
    autoLearnChip: document.getElementById('autoLearnChip'),
    autoAcceptanceChip: document.getElementById('autoAcceptanceChip'),
    autoLearnMenuWrap: document.getElementById('autoLearnMenuWrap'),
    autoLearnMenuBtn: document.getElementById('autoLearnMenuBtn'),
    autoLearnMenuList: document.getElementById('autoLearnMenuList'),
    viewLearningDataItem: document.getElementById('viewLearningDataItem'),
    resetResidualsItem: document.getElementById('resetResidualsItem'),
    resetMeaningsCurrentItem: document.getElementById('resetMeaningsCurrentItem'),
    resetMeaningsAllItem: document.getElementById('resetMeaningsAllItem'),
    learningToolbarBtn: document.getElementById('learningToolbarBtn'),
    learningToolbarChip: document.getElementById('learningToolbarChip'),
    autoStatusChip: document.getElementById('autoStatusChip'),
    autoStepIndicator: document.getElementById('autoStepIndicator'),
    visionEngineChip: document.getElementById('visionEngineChip'),
    styleIdInput: document.getElementById('styleIdInput'),
  };

  let ctx = el.canvas.getContext('2d');

  // Image pixel data is stored once per image id here, so history snapshots can
  // reference images by id instead of carrying (and re-serializing) base64 copies.
  const imageDataById = new Map();
